FROM openjdk:8-jdk-alpine

VOLUME /tmp

ARG DATASOURCE_URL_ARG="jdbc:mysql://mysql:3306/simple_aws_aurora_schema?useSSL=false"
ARG DATASOURCE_USERNAME_ARG="root"
ARG DATASOURCE_PASSWORD_ARG="hS34%68rt"
ARG DATASOURCE_DRIVER_NAME_ARG="com.mysql.jdbc.Driver"
ARG DATASOURCE_DIALECT_ARG="org.hibernate.dialect.MySQL57Dialect"
ARG DATASOURCE_DDL_AUTO_ARG="update"

COPY build/libs/*.jar app.jar

ENV DATASOURCE_URL=$DATASOURCE_URL_ARG
ENV DATASOURCE_USERNAME=$DATASOURCE_USERNAME_ARG
ENV DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD_ARG
ENV DATASOURCE_DRIVER_NAME=$DATASOURCE_DRIVER_NAME_ARG
ENV DATASOURCE_DIALECT=$DATASOURCE_DIALECT_ARG
ENV DATASOURCE_DDL_AUTO=$DATASOURCE_DDL_AUTO_ARG

RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]